### ISSUE TITLE
Disabling Teleport

### ISSUE THREAD

**Issue by kestral246** [minetest-mods/ccompass#11]
What is the official method for disabling the teleport feature of this mod?

Adding the following line to minetest.conf seems to work:
`ccompass_teleport_nodes =`
with nothing after the '=', but that looks rather odd to me.

Would it make more sense to add another option to specifically enable/disable this feature?

**Comment by bell07** [comment]
There is no "official" method.  If nothing looks odd, you just can set anything invalid like `ccompass_teleport_nodes = none`

**Comment by kestral246** [comment]
Thanks.
Would it be possible to add this to the readme file?
It wasn't obvious to me at first how to do this.

**Comment by bell07** [comment]
Done in 9845a89ec50f4a4066129286cdcb0128c0b49d32
