### ISSUE TITLE
Calibrate sound

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/ccompass#2]
I'm thinking the last part of [this sound](http://www.freesound.org/people/beskhu/sounds/273910/). Will try to do a PR for it.

**Comment by bell07** [comment]
I added success message in chat. I think it should be the right place for playing sound...

**Comment by tacotexmex** [comment]
Hey, found another apt sound for the compass, but I'm not entirely sure it's better. What do you think? 

https://clyp.it/j1kjuejj

**Comment by bell07** [comment]
I am not not an "Aesthetic guy" to be able to decide something for sounds or textures. So it is your choice. If you take a PR I will merge it.

I like the first sound more, the new one is to "mechanic", the first one was a little bit "mystic" for me.

**Comment by tacotexmex** [comment]
> the new one is to "mechanic", the first one was a little bit "mystic" for me.

You're right, mystic over mechanic!
