### ISSUE TITLE
Conflict with digtron

### ISSUE THREAD

**Issue by VorTechnix** [minetest-mods/ccompass#22]
The ccompass recipe is used for the digtron core.
![image](https://user-images.githubusercontent.com/45538536/140659193-27b67aac-2d8d-49fa-9c1b-651cbdb0abb2.png)
Might I suggest this recipe instead:
![image](https://user-images.githubusercontent.com/45538536/140659223-9057f2c5-d195-454d-a9b9-f25279c2fcba.png)

**Comment by nixnoxus** [comment]
therefore an alternative recipe was added in #19

**Comment by VorTechnix** [comment]
thanks, I didn't realize there was an update.
