### ISSUE TITLE
Request increased number of pointing directions

### ISSUE THREAD

**Issue by Golutazem** [minetest-mods/ccompass#9]
This request is for an increased number of pointing directions.
8 or a multiple of that would be good. The easiest directions to walk in minetest are in the directions of block alignment, N,E,S,W and diagonally, NE,SE,SW,NW, therefore it would be most useful to have the compass point in those directions.

**Comment by bell07** [comment]
Compas does have 12 directories currently that is more then 8. For me it is ok...
@tacotexmex, what do you think? 8 or 16? If you like the idea, we need new textures..

**Comment by tacotexmex** [comment]
There _may_ be time for me to do 16 directions textures. It does make sense to use a factor of 8 to decide number of directions.

**Comment by kestral246** [comment]
Don't change the textures to 16 directions unless you do a full animation analysis that looks as good as the 12-direction textures.
I really wanted to use 16 directions for my realcompass mod, but all my designs animated like the needle was made with a wet noodle.
When tacotexmex suggested I use his textures, I converted back to 12 directions, since I couldn't come up with a 16-direction version that had as smooth and even of an animation as his 12-direction design.

**Comment by tacotexmex** [comment]
The needle _is_ a wet noodle, but with the source file still available i should be able to make it work with 16 dirs as well. Do you want it @bell07?

**Comment by bell07** [comment]
I like the 12 directions. But we can push the 16- directions version to separate git branch. Decide you, in lua just 2 lines needs to be adjusted.

**Comment by tacotexmex** [comment]
It’s almost done, but it’s also summer…
```
🧭       🍸
 ¯\_(ツ)_/¯

**Comment by tacotexmex** [comment]
The textures must be named differently though, to not break texture pack compatibility. Ok? 🙂

**Comment by bell07** [comment]
Adjusted, pushed working change to https://github.com/minetest-mods/ccompass/tree/16dirs branch. 
Now I going to setup poll in forum which of the versions should be

**Comment by kestral246** [comment]
@tacotexmex,

Shouldn't the needles for ccompass_16_3 and ccompass_16_13 be mirror images of each other? Right now they're not.

I'm working on converting the colors to work with my realcompass mod. I hope that's still OK with you.

**Comment by kestral246** [comment]
@tacotexmex,

I'm considering a few minor tweaks to your 16-direction textures as I'm continuing my conversion for realcompass.

I created a temporary github repo, if you're interested in taking a look.
[https://github.com/kestral246/16dirs](https://github.com/kestral246/16dirs)

**Comment by tacotexmex** [comment]
> Shouldn't the needles for ccompass_16_3 and ccompass_16_13 be mirror images of each other

I don't see why it should.
